// import 'dart:convert';
// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:flutter/services.dart';
// import 'package:vfarm/models/daily_activity_model.dart';
// import 'package:vfarm/session_manager.dart';
// import 'package:vfarm/models/user_profile_model.dart';
// import 'dart:math';

// class FarmActivityService {
//   static FarmActivityService? _instance;
//   static FarmActivityService get instance => _instance ??= FarmActivityService._();
  
//   FarmActivityService._();
  
//   final FirebaseFirestore _firestore = FirebaseFirestore.instance;
//   Map<String, dynamic>? _activityPredictionModel;
//   bool _initialized = false;
  
//   static const String _lastPromptKey = 'last_daily_prompt_date';
//   static const String _skippedPromptKey = 'skipped_daily_prompt_date';
  
//   Future<void> initialize() async {
//     if (_initialized) return;
    
//     try {
//       // Load the JSON model generated by Python script
//       await _loadPredictionModel();
//       _initialized = true;
//       print('✅ Farm Activity Service initialized');
//     } catch (e) {
//       print('❌ Error initializing Farm Activity Service: $e');
//       // Continue without the model - will use fallback suggestions
//       _initialized = true;
//     }
//   }
  
//   Future<void> _loadPredictionModel() async {
//     try {
//       // Try to load from assets (if you place the JSON there)
//       final String jsonString = await rootBundle.loadString('assets/simple_farm_model.json');
//       _activityPredictionModel = json.decode(jsonString);
//       print('✅ Prediction model loaded from assets');
//     } catch (e) {
//       print('⚠️  Could not load prediction model from assets: $e');
//       // Use fallback model
//       _createFallbackModel();
//     }
//   }
  
//   void _createFallbackModel() {
//     _activityPredictionModel = {
//       'activity_patterns': {
//         'month': {
//           '9': {'Irrigation': 0.3, 'Fertilizer Application': 0.25, 'Weeding': 0.2, 'Ploughing': 0.15, 'Harvesting': 0.1},
//           '10': {'Harvesting': 0.4, 'Threshing': 0.25, 'Storage': 0.15, 'Irrigation': 0.1, 'Ploughing': 0.1},
//           '11': {'Ploughing': 0.35, 'Sowing': 0.3, 'Irrigation': 0.2, 'Fertilizer Application': 0.15},
//           '12': {'Sowing': 0.4, 'Irrigation': 0.25, 'Fertilizer Application': 0.2, 'Weeding': 0.15},
//         },
//         'season_crop': {
//           'Kharif_Paddy': {'Irrigation': 0.3, 'Fertilizer Application': 0.25, 'Weeding': 0.2, 'Harvesting': 0.15, 'Ploughing': 0.1},
//           'Rabi_Paddy': {'Sowing': 0.3, 'Irrigation': 0.25, 'Fertilizer Application': 0.2, 'Ploughing': 0.15, 'Weeding': 0.1},
//           'Kharif_Coconut': {'Irrigation': 0.25, 'Fertilizer Application': 0.2, 'Weeding': 0.2, 'Harvesting': 0.2, 'Pesticide Spray': 0.15},
//           'Rabi_Coconut': {'Fertilizer Application': 0.3, 'Irrigation': 0.25, 'Weeding': 0.2, 'Pesticide Spray': 0.15, 'Harvesting': 0.1},
//         },
//         'district_crop': {
//           'Ernakulam_Paddy': {'Irrigation': 0.3, 'Fertilizer Application': 0.25, 'Weeding': 0.2, 'Harvesting': 0.15, 'Ploughing': 0.1},
//           'Thiruvananthapuram_Coconut': {'Harvesting': 0.3, 'Irrigation': 0.25, 'Fertilizer Application': 0.2, 'Weeding': 0.15, 'Pesticide Spray': 0.1},
//           'Kozhikode_Rubber': {'Tapping': 0.4, 'Fertilizer Application': 0.2, 'Weeding': 0.2, 'Irrigation': 0.1, 'Pesticide Spray': 0.1},
//         }
//       }
//     };
//     print('✅ Fallback prediction model created');
//   }
  
//   Future<bool> shouldShowDailyPrompt() async {
//     try {
//       final sessionManager = SessionManager.instance;
//       final userId = sessionManager.getCurrentUserId();
      
//       if (userId == null) return false;
      
//       final today = DateTime.now();
//       final todayStr = _formatDate(today);
      
//       // Check if already prompted today
//       final userDoc = await _firestore.collection('daily_activities').doc(userId).get();
      
//       if (userDoc.exists) {
//         final data = userDoc.data() as Map<String, dynamic>;
//         final lastPromptDate = data[_lastPromptKey] as String?;
//         final skippedDate = data[_skippedPromptKey] as String?;
        
//         // If already prompted or skipped today, don't show again
//         if (lastPromptDate == todayStr || skippedDate == todayStr) {
//           return false;
//         }
        
//         // Check if user has already logged activity today
//         final activities = data['activities'] as List<dynamic>? ?? [];
//         for (var activity in activities) {
//           if (activity['date'] == todayStr) {
//             return false; // Already logged activity today
//           }
//         }
//       }
      
//       return true; // Show prompt
//     } catch (e) {
//       print('Error checking daily prompt: $e');
//       return false;
//     }
//   }
  
//   Future<List<ActivitySuggestion>> getTodaysSuggestions() async {
//     try {
//       final profile = SessionManager.instance.getCurrentUserProfile();
//       if (profile == null) {
//         return _getFallbackSuggestions();
//       }
      
//       final suggestions = await _generateSuggestions(profile);
//       return suggestions.isNotEmpty ? suggestions : _getFallbackSuggestions();
//     } catch (e) {
//       print('Error getting suggestions: $e');
//       return _getFallbackSuggestions();
//     }
//   }
  
//   Future<List<ActivitySuggestion>> _generateSuggestions(UserProfileModel profile) async {
//     if (_activityPredictionModel == null) {
//       return _getFallbackSuggestions();
//     }
    
//     final now = DateTime.now();
//     final month = now.month.toString();
//     final season = _getCurrentSeason(now);
    
//     // Get user's primary crop (first in the list)
//     final primaryCrop = profile.cropTypes.isNotEmpty ? profile.cropTypes.first : 'Paddy';
    
//     // Get location (extract district from farmLocation if available)
//     final district = _extractDistrict(profile.farmLocation);
    
//     Map<String, double> activityScores = {};
    
//     // Pattern matching from the model
//     final patterns = _activityPredictionModel!['activity_patterns'] as Map<String, dynamic>;
    
//     // Month-based suggestions (weight: 40%)
//     if (patterns['month'] != null && patterns['month'][month] != null) {
//       final monthPatterns = patterns['month'][month] as Map<String, dynamic>;
//       monthPatterns.forEach((activity, score) {
//         activityScores[activity] = (activityScores[activity] ?? 0) + (score as double) * 0.4;
//       });
//     }
    
//     // Season + Crop suggestions (weight: 30%)
//     final seasonCropKey = '${season}_$primaryCrop';
//     if (patterns['season_crop'] != null && patterns['season_crop'][seasonCropKey] != null) {
//       final seasonCropPatterns = patterns['season_crop'][seasonCropKey] as Map<String, dynamic>;
//       seasonCropPatterns.forEach((activity, score) {
//         activityScores[activity] = (activityScores[activity] ?? 0) + (score as double) * 0.3;
//       });
//     }
    
//     // District + Crop suggestions (weight: 20%)
//     if (district != null) {
//       final districtCropKey = '${district}_$primaryCrop';
//       if (patterns['district_crop'] != null && patterns['district_crop'][districtCropKey] != null) {
//         final districtCropPatterns = patterns['district_crop'][districtCropKey] as Map<String, dynamic>;
//         districtCropPatterns.forEach((activity, score) {
//           activityScores[activity] = (activityScores[activity] ?? 0) + (score as double) * 0.2;
//         });
//       }
//     }
    
//     // Convert to suggestions and sort by score
//     final suggestions = activityScores.entries
//         .map((entry) => ActivitySuggestion(
//               activity: entry.key,
//               confidence: entry.value,
//               priority: _getPriorityLevel(entry.value),
//               description: _getActivityDescription(entry.key),
//               icon: _getActivityIcon(entry.key),
//             ))
//         .toList();
    
//     suggestions.sort((a, b) => b.confidence.compareTo(a.confidence));
    
//     // Return top 5 suggestions
//     return suggestions.take(5).toList();
//   }
  
//   List<ActivitySuggestion> _getFallbackSuggestions() {
//     final now = DateTime.now();
//     final month = now.month;
    
//     List<ActivitySuggestion> fallbackSuggestions;
    
//     // Season-based fallback suggestions
//     if (month >= 6 && month <= 9) {
//       // Monsoon season
//       fallbackSuggestions = [
//         ActivitySuggestion(
//           activity: 'Irrigation',
//           confidence: 0.8,
//           priority: 'High',
//           description: 'Monitor and manage water levels in your fields',
//           icon: '💧',
//         ),
//         ActivitySuggestion(
//           activity: 'Weeding',
//           confidence: 0.7,
//           priority: 'High',
//           description: 'Remove weeds that grow rapidly in monsoon',
//           icon: '🌿',
//         ),
//         ActivitySuggestion(
//           activity: 'Fertilizer Application',
//           confidence: 0.6,
//           priority: 'Medium',
//           description: 'Apply organic fertilizers during monsoon',
//           icon: '🌱',
//         ),
//       ];
//     } else if (month >= 10 && month <= 1) {
//       // Post-monsoon/Winter
//       fallbackSuggestions = [
//         ActivitySuggestion(
//           activity: 'Harvesting',
//           confidence: 0.9,
//           priority: 'High',
//           description: 'Harvest mature crops before winter',
//           icon: '🌾',
//         ),
//         ActivitySuggestion(
//           activity: 'Ploughing',
//           confidence: 0.7,
//           priority: 'Medium',
//           description: 'Prepare fields for next season',
//           icon: '🚜',
//         ),
//         ActivitySuggestion(
//           activity: 'Storage',
//           confidence: 0.6,
//           priority: 'Medium',
//           description: 'Store harvested crops properly',
//           icon: '🏪',
//         ),
//       ];
//     } else {
//       // Summer season
//       fallbackSuggestions = [
//         ActivitySuggestion(
//           activity: 'Irrigation',
//           confidence: 0.9,
//           priority: 'High',
//           description: 'Essential watering during hot season',
//           icon: '💧',
//         ),
//         ActivitySuggestion(
//           activity: 'Sowing',
//           confidence: 0.7,
//           priority: 'Medium',
//           description: 'Plant summer crops',
//           icon: '🌱',
//         ),
//         ActivitySuggestion(
//           activity: 'Pesticide Spray',
//           confidence: 0.6,
//           priority: 'Medium',
//           description: 'Protect crops from summer pests',
//           icon: '🛡️',
//         ),
//       ];
//     }
    
//     return fallbackSuggestions;
//   }
  
//   Future<void> saveUserActivity({
//     required String activity,
//     String? notes,
//     bool isCompleted = true,
//   }) async {
//     try {
//       final sessionManager = SessionManager.instance;
//       final userId = sessionManager.getCurrentUserId();
//       final profile = sessionManager.getCurrentUserProfile();
      
//       if (userId == null || profile == null) {
//         throw Exception('User not authenticated');
//       }
      
//       final now = DateTime.now();
//       final todayStr = _formatDate(now);
      
//       final activityData = DailyActivityModel(
//         id: '${userId}_${todayStr}_${now.millisecondsSinceEpoch}',
//         userId: userId,
//         date: now,
//         activity: activity,
//         notes: notes,
//         isCompleted: isCompleted,
//         farmLocation: profile.farmLocation,
//         cropTypes: profile.cropTypes,
//         farmSize: profile.farmSize,
//         createdAt: now,
//       );
      
//       // Save to Firestore
//       final docRef = _firestore.collection('daily_activities').doc(userId);
      
//       await _firestore.runTransaction((transaction) async {
//         final doc = await transaction.get(docRef);
        
//         if (doc.exists) {
//           final existingData = doc.data() as Map<String, dynamic>;
//           final activities = List<Map<String, dynamic>>.from(existingData['activities'] ?? []);
          
//           // Check if activity already exists for today
//           final existingIndex = activities.indexWhere((a) => a['date'] == todayStr);
          
//           if (existingIndex >= 0) {
//             // Update existing activity
//             activities[existingIndex] = activityData.toMap();
//           } else {
//             // Add new activity
//             activities.add(activityData.toMap());
//           }
          
//           transaction.update(docRef, {
//             'activities': activities,
//             _lastPromptKey: todayStr,
//             'lastUpdated': FieldValue.serverTimestamp(),
//           });
//         } else {
//           // Create new document
//           transaction.set(docRef, {
//             'userId': userId,
//             'activities': [activityData.toMap()],
//             _lastPromptKey: todayStr,
//             'createdAt': FieldValue.serverTimestamp(),
//             'lastUpdated': FieldValue.serverTimestamp(),
//           });
//         }
//       });
      
//       print('✅ Activity saved successfully');
//     } catch (e) {
//       print('❌ Error saving activity: $e');
//       throw e;
//     }
//   }
  
//   Future<void> markDailyPromptSkipped() async {
//     try {
//       final sessionManager = SessionManager.instance;
//       final userId = sessionManager.getCurrentUserId();
      
//       if (userId == null) return;
      
//       final todayStr = _formatDate(DateTime.now());
      
//       await _firestore.collection('daily_activities').doc(userId).set({
//         _skippedPromptKey: todayStr,
//         'lastUpdated': FieldValue.serverTimestamp(),
//       }, SetOptions(merge: true));
      
//       print('✅ Daily prompt marked as skipped');
//     } catch (e) {
//       print('❌ Error marking prompt as skipped: $e');
//     }
//   }
  
//   Future<List<DailyActivityModel>> getUserActivities({
//     int? limitDays,
//   }) async {
//     try {
//       final sessionManager = SessionManager.instance;
//       final userId = sessionManager.getCurrentUserId();
      
//       if (userId == null) return [];
      
//       final doc = await _firestore.collection('daily_activities').doc(userId).get();
      
//       if (!doc.exists) return [];
      
//       final data = doc.data() as Map<String, dynamic>;
//       final activities = data['activities'] as List<dynamic>? ?? [];
      
//       List<DailyActivityModel> userActivities = activities
//           .map((a) => DailyActivityModel.fromMap(a as Map<String, dynamic>))
//           .toList();
      
//       // Sort by date (newest first)
//       userActivities.sort((a, b) => b.date.compareTo(a.date));
      
//       // Apply limit if specified
//       if (limitDays != null) {
//         final cutoffDate = DateTime.now().subtract(Duration(days: limitDays));
//         userActivities = userActivities
//             .where((activity) => activity.date.isAfter(cutoffDate))
//             .toList();
//       }
      
//       return userActivities;
//     } catch (e) {
//       print('❌ Error getting user activities: $e');
//       return [];
//     }
//   }
  
//   // Utility methods
//   String _formatDate(DateTime date) {
//     return '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
//   }
  
//   String _getCurrentSeason(DateTime date) {
//     final month = date.month;
//     if (month >= 6 && month <= 9) {
//       return 'Kharif';
//     } else if (month >= 10 && month <= 3) {
//       return 'Rabi';
//     } else {
//       return 'Summer';
//     }
//   }
  
//   String? _extractDistrict(String? farmLocation) {
//     if (farmLocation == null) return null;
    
//     // List of Kerala districts for matching
//     final districts = [
//       'Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 
//       'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad',
//       'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'
//     ];
    
//     final location = farmLocation.toLowerCase();
//     for (final district in districts) {
//       if (location.contains(district.toLowerCase())) {
//         return district;
//       }
//     }
    
//     return null;
//   }
  
//   String _getPriorityLevel(double confidence) {
//     if (confidence >= 0.3) return 'High';
//     if (confidence >= 0.15) return 'Medium';
//     return 'Low';
//   }
  
//   String _getActivityDescription(String activity) {
//     const descriptions = {
//       'Ploughing': 'Prepare your field by ploughing the soil',
//       'Sowing': 'Plant seeds or seedlings in your field',
//       'Irrigation': 'Water your crops for healthy growth',
//       'Fertilizer Application': 'Apply fertilizers to boost crop nutrition',
//       'Pesticide Spray': 'Protect crops from pests and diseases',
//       'Weeding': 'Remove unwanted weeds from your field',
//       'Harvesting': 'Harvest mature crops from your field',
//       'Threshing': 'Separate grains from harvested crops',
//       'Storage': 'Store your harvested produce properly',
//       'Tapping': 'Collect rubber latex from trees',
//     };
    
//     return descriptions[activity] ?? 'Perform $activity activity';
//   }
  
//   String _getActivityIcon(String activity) {
//     const icons = {
//       'Ploughing': '🚜',
//       'Sowing': '🌱',
//       'Irrigation': '💧',
//       'Fertilizer Application': '🌿',
//       'Pesticide Spray': '🛡️',
//       'Weeding': '🌾',
//       'Harvesting': '🌾',
//       'Threshing': '🌾',
//       'Storage': '🏪',
//       'Tapping': '🪣',
//     };
    
//     return icons[activity] ?? '🌱';
//   }
// }// TODO Implement this library.
